-- Храним только то, без чего бот не работает: externalId, имя, роль, класс.
-- Никаких оценок, здоровья, дисциплины.

CREATE TABLE classes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    -- nullable: класс и учитель ссылаются друг на друга, вставляем класс -> учителя -> проставляем teacher_id
    teacher_id BIGINT
);

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- id во внешней системе (VK). У ученика может не быть аккаунта, поэтому nullable.
    external_id VARCHAR(64),
    role        VARCHAR(16)  NOT NULL,
    class_id    BIGINT REFERENCES classes (id),
    full_name   VARCHAR(200) NOT NULL,
    -- у STUDENT — его родитель, через него уходят напоминания о дежурстве
    parent_id   BIGINT REFERENCES users (id),
    CONSTRAINT uq_users_external_id UNIQUE (external_id),
    CONSTRAINT ck_users_role CHECK (role IN ('TEACHER', 'PARENT', 'STUDENT'))
);

CREATE INDEX idx_users_class_role ON users (class_id, role);

ALTER TABLE classes
    ADD CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) REFERENCES users (id);

CREATE TABLE announcements (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id          BIGINT        NOT NULL REFERENCES classes (id),
    author_id         BIGINT        NOT NULL REFERENCES users (id),
    text              VARCHAR(4000) NOT NULL,
    -- true: родитель отвечает «Согласен / Не смогу», false: достаточно «Прочитал»
    requires_decision BOOLEAN       NOT NULL DEFAULT FALSE,
    deadline          TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    attachment_url    VARCHAR(1000)
);

CREATE INDEX idx_announcements_class_created ON announcements (class_id, created_at);

-- PK (announcement_id, user_id): повторный клик не может породить вторую строку
CREATE TABLE announcement_reads (
    announcement_id BIGINT NOT NULL REFERENCES announcements (id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    read_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    decision        VARCHAR(16),
    PRIMARY KEY (announcement_id, user_id),
    CONSTRAINT ck_announcement_reads_decision CHECK (decision IS NULL OR decision IN ('AGREE', 'DECLINE'))
);

CREATE TABLE polls (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id   BIGINT        NOT NULL REFERENCES classes (id),
    type       VARCHAR(16)   NOT NULL,
    question   VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_polls_type CHECK (type IN ('CONSENT', 'CHOICE', 'CUSTOM'))
);

CREATE INDEX idx_polls_class_created ON polls (class_id, created_at);

CREATE TABLE poll_options (
    poll_id  BIGINT       NOT NULL REFERENCES polls (id) ON DELETE CASCADE,
    position INT          NOT NULL,
    label    VARCHAR(200) NOT NULL,
    PRIMARY KEY (poll_id, position)
);

-- один ответ на человека; смена ответа — UPDATE, не новая строка
CREATE TABLE poll_answers (
    poll_id     BIGINT        NOT NULL REFERENCES polls (id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL REFERENCES users (id),
    answer      VARCHAR(1000) NOT NULL,
    answered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (poll_id, user_id)
);

CREATE TABLE calendar_events (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT       NOT NULL REFERENCES classes (id),
    type     VARCHAR(16)  NOT NULL,
    title    VARCHAR(300) NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_calendar_events_type CHECK (type IN ('DUTY', 'EVENT', 'MEETING'))
);

CREATE INDEX idx_calendar_events_class_start ON calendar_events (class_id, start_at);

-- за сколько минут до start_at напомнить (1440 = за день, 60 = за час)
CREATE TABLE calendar_event_reminder_offsets (
    event_id       BIGINT NOT NULL REFERENCES calendar_events (id) ON DELETE CASCADE,
    offset_minutes INT    NOT NULL,
    PRIMARY KEY (event_id, offset_minutes),
    CONSTRAINT ck_reminder_offset_positive CHECK (offset_minutes > 0)
);

CREATE TABLE duty_schedules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id       BIGINT NOT NULL REFERENCES classes (id),
    student_id     BIGINT NOT NULL REFERENCES users (id),
    duty_date      DATE   NOT NULL,
    rotation_order INT    NOT NULL,
    CONSTRAINT uq_duty_schedules_class_date UNIQUE (class_id, duty_date)
);
